name: GRPC Server CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up AOSP env
        run: |
          cd /home/farah/android-aosp
          source build/envsetup.sh
          lunch 14

  connect:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Check ADB status
        run: |
          echo ">>> Killing ADB server"
          sudo adb kill-server
          echo ">>> Starting ADB server"
          sudo adb start-server
          echo ">>> Listing devices"
          sudo adb devices
          echo ">>> Connecting to emulator/device"
          sudo adb connect 0.0.0.0:6520 || echo "Connection failed"
          echo ">>> Devices after connect"
          sudo adb devices



  deploy:
    runs-on: self-hosted
    needs: connect
    steps:
      - name: Start gRPC Server
        run: |
          sudo adb devices
          sudo adb root
          sudo adb shell "vendor/bin/grpc_server" > grpc_server.log 2>&1 &
          sleep 30
          if adb shell "ps | grep grpc_server"; then echo "Server is running"; else echo "Server failed to start"; exit 1; fi
          touch /tmp/finished_indicator_file

  trigger-client:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Trigger Client Pipeline
        run: |
          curl -X POST -F token=glptt-6aa890b66b4ae0c7165e7e4e64aa8086d4781004 -F ref=main https://gitlab.com/api/v4/projects/68155819/trigger/pipeline

