name: GRPC Server CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up AOSP env
        run: |
          cd /home/farah/android-aosp
          source build/envsetup.sh
          lunch 14

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Start gRPC Server
        run: |
          adb devices
          adb root
          sleep 5
          adb devices
          echo ">>> Trying to run gRPC server"
          adb shell "ls vendor/bin"
          adb shell "which grpc_server" || echo "grpc_server not found"
          adb shell "vendor/bin/grpc_server" > /tmp/grpc_server.log 2>&1 &
          sleep 30
          echo ">>> Checking if server started"
          adb shell "ps | grep grpc_server" || echo "Server not found in process list"
          if adb shell "ps | grep grpc_server"; then echo "Server is running"; else echo "Server failed to start"; exit 1; fi

  trigger-client:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Trigger Client Pipeline
        run: |
          curl -X POST -F token=glptt-6aa890b66b4ae0c7165e7e4e64aa8086d4781004 -F ref=main https://gitlab.com/api/v4/projects/68155819/trigger/pipeline

